language: csharp
mono: none
dotnet: 2.1.300
addons:
  apt:
    packages:
    - zlib1g
    - fontconfig
    - libfreetype6
    - libx11-6
    - libxext6
    - libxrender1
script:
  - dotnet tool install -g dotnet-deathworlders-md-convert
  - export PATH="$PATH:/home/travis/.dotnet/tools"
  - cd tools/markdown-converter/
  - ./generate-all.sh